language: python
python:
  - 2.7
sudo: false
cache:
  directories:
  - eggs
  - downloads
env:
  - PLONE_VERSION=4.3
  - PLONE_VERSION=5.0
  - PLONE_VERSION=5.1
matrix:
  fast_finish: true
addons:
  firefox: 45.8.0esr
install:
  - sed -ie "s#test-4.x.cfg#test-$PLONE_VERSION.x.cfg#" travis.cfg
  - sed -ie "s#versions-$PLONE_VERSION.x#versions#" travis.cfg
  - mkdir -p buildout-cache/eggs
  - mkdir -p buildout-cache/downloads
  - pip install zc.buildout==2.5.0
  - buildout -c travis.cfg annotate
  - buildout -c travis.cfg -N -q

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - firefox -v
script:
  - bin/code-analysis
  - bin/test
after_success:
  - bin/createcoverage
  - pip install coveralls
  - coveralls
